project:
  type: book
  output-dir: ../_build/book

book:
  title: "EMSC-2010: Data Science for Earth System Scientists"
  author:
    - "Louis Moresi"
  date: "06/03/2024"
  bread-crumbs: True
  chapters:
    - part: "Course Information"
      chapters:
        - index.qmd
        - about.qmd
        - construction-plan.qmd
    - part: "Week 1-4: Foundations"
      chapters:
        - intro.qmd
    - part: "Week 5-12: Applications"
      chapters:
        - summary.qmd
        - references.qmd

    - part: "Slides"
      chapters:
        - LectureSlides/Lecture1.qmd

  appendices:
    - Notebooks/BinderLandingPage.qmd
    - Notebooks/TestNB1.ipynb
    - Notebooks/TestQMD_NB1.qmd

  navbar:
    search: true
    logo: assets/ANU-logo.png
    background: "#00A86B"  # Intense jade green
    foreground: white
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Construction Plan"
        href: construction-plan.qmd
      - text: "Foundations"
        href: intro.qmd
    right:
      - icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-2010
        aria-label: GitHub

  sidebar:
    logo: assets/AuWorldEQ.jpg
    style: "docked"
    background: light

bibliography: references.bib

execute:
  enabled: false

format:
  live-html:
    theme: [cosmo, "assets/theme.scss"]
    css: assets/styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: false
    linkcolor: "#00A86B"
    number-sections: false
    number-depth: 1
    # filters:
    #   - pyodide

    # code-links:
    #   - text: Open in Binder
    #     icon: rocket-takeoff
    #     href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-QuartoBook/HEAD?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd

    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-QuartoBook

  # pdf:
  #   documentclass: scrreprt

pyodide:
  packages:
    - micropip
    - netcdf4
    - xarray
    - pydap
    - jinja2
    - ssl
    - owslib
